services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    depends_on:
      - db

  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - "file_storage:/app/storage"
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started

volumes:
  pgdata:
  file_storage:
