services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  valkey:
    image: valkey/valkey:latest
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - backend

  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - "file_storage:/app/storage"
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
    networks:
      - backend
      - frontend

volumes:
  pgdata:
  file_storage:
    
networks:
  backend:
    driver: bridge
    name: backend_private
  frontend:
    driver: bridge
    name: frontend_public
